name: Publish Website

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Publish-Website:
    name: Publish-Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove .git directory
        run: rm -rf .git

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: wpcom
          path: .
          retention-days: 1
