name: Publish Website

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Publish-Website:
    name: Publish-Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: wpcom
          path: |
            .
            !.git*
          retention-days: 1
